### PR TITLE
REFORMAT AND BETTER SHIT

### PR DESCRIPTION
**Pull request by sn3akrr**
PLEASE LEARN PHP I FIXED ALL THE STYLING AND YOUR CODING MISTAKES

### CODE REVIEW

**Comment by xZeroMCPE** [comment]
Accept the code already... Previous one was messy

**Comment by SirMinerDev** [comment]
Not everyone has to code like you ;)

**Comment by sn3akrr** [comment]
Dude. You can't even consider this code, it's fucking garbage, that is not how you code. Keep practicing shitty styling and inconsistency no one will want to use your code, just a word of advice.

**Comment by SirMinerDev** [comment]
Who gives a fuck if someone wants to use the code or not.

**Comment by sn3akrr** [comment]
You should..?? Otherwise it's pretty useless, what's the point of coding it, you're just showing everyone how bad the code is lol

**Comment by buchwasa** [comment]
Please merge this PR, the code on here is absolute shit without @mal0ne-23's PR

**Comment by LordGitjob** [comment]
There's no need to be an ass hole about it. Surely you could have gave constructive criticism rather than coming in guns blazing. @mal0ne-23

**Comment by sn3akrr** [comment]
> constructive criticism

sorry im bad at this im pretty blunt 😆

**Comment by sn3akrr** [comment]
so you're not going to accept it..? okay

**Pull request closed without merging**
